# GitHub 构建 Java 应用
# ln $workingDir/peacetrue.github.io/docs/antora/modules/ROOT/examples/java-gradle-build.yml main.yml
name: build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

# https://github.com/mikepenz/action-junit-report/issues/23
permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    # https://github.com/actions/setup-java#testing-against-different-java-versions
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
    name: Java ${{ matrix.Java }} Build
    steps:
      - uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

#          https://github.com/gradle/gradle-build-action
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.4
          arguments: build

      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}
      # token: ${{ secrets.TESTSPACE_TOKEN }} # optional, only required for private repos

      - name: Publish Results to Testspace
        run: testspace "build/test-results/test/*.xml" "build/reports/jacoco/test/jacocoTestReport.xml"

      # https://github.com/gradle/gradle-build-action/issues/619
      # https://github.com/marketplace/actions/junit-report-action
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      # https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions
      #https://github.com/marketplace/actions/codecov
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        if: success()
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
#        files: ./coverage1.xml,./coverage2.xml # optional
#        flags: unittests # optional
#        name: codecov-umbrella # optional
#        fail_ci_if_error: true # optional (default = false)
#        verbose: true # optional (default = false)
